### PR TITLE
redefine Science and Education to comply with guidelines

### PR DESCRIPTION
**Pull request by bnavigator**
if you don't want to discard the whole test (#14), at least fix the categories according to the guidelines (https://en.opensuse.org/openSUSE:Packaging_desktop_menu_categories). Fixes the specific mentioned categories in #4 

Other categories than Science and Education possibly still need to be updated to the current guidelines.

### CODE REVIEW

**Comment by coolo** [comment]
I can merge this (as there doesn't seem to be maintainers :cry: ), but I can't predict what it causes. So are you willing to monitor the fallout?

**Comment by bnavigator** [comment]
Yes I can watch the opensuse bugzilla and GitHub issues here regarding the Science and Engineering desktop categories.

**Comment by coolo** [comment]
submitted to Base:System

**Comment by krop** [comment]
The SR was accepted and we're seeing build failures in KDE packages.
eg: 

> [  135s] ERROR: No sufficient Category definition "Qt;KDE;Education;X-KDE-Edu-Misc;X-KDE-Edu-Teaching;"

As `X-KDE-Edu-Teaching` is still recognized, that leaves `X-KDE-Edu-Misc` which is valid:

> Categories not in this document must be prefixed by the string "X-" indicating that they are extensions. Categories are case-sensitive. 

(https://standards.freedesktop.org/menu-spec/latest/ar01s03.html)

**Comment by bnavigator** [comment]
No, it fails because if X-KDE-Edu-Teaching not being recognized by the macro. See #27 for a fix

**Comment by krop** [comment]
Well, we're seeing issues in other areas now as well. See https://github.com/openSUSE/brp-check-suse/issues/26

**Pull request merged**
