### PR TITLE
Add NO_BRP_AR as a way how to skip ar.

### PR DESCRIPTION
**Pull request by marxin**
It would be useful for Go packages:
https://github.com/golang/go/issues/17890

### CODE REVIEW

**Comment by marxin** [comment]
@sleep-walker

**Comment by bmwiedemann** [comment]
So how sure are we that objcopy screws go's extra info in .a files?
I hope, objcopy will then still be called for non-go packages. Then I'm fine with it.

**Comment by bmwiedemann** [comment]
one thing: please add some more detail about "Why" in the commit message. Links to bugtrackers can go stale some day and finding the relevant part in it is also not always easy.

**Comment by marxin** [comment]
> So how sure are we that objcopy screws go's extra info in .a files?

Very sure.

> I hope, objcopy will then still be called for non-go packages. Then I'm fine with it.

Yes, that's our intention.

**Comment by marxin** [comment]
> one thing: please add some more detail about "Why" in the commit message. Links to bugtrackers can go stale some day and finding the relevant part in it is also not always easy.

Done.

**Comment by marxin** [comment]
Can please anybody merge the PR now?

**Pull request merged**
